baseURL = "https://example.com/"
languageCode = "en-us"
title = "Lorem Mandapam"
theme = ["github.com/ananthb/mandapam-theme"]

enableGitInfo = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  google_analytics_id = ""
  github_repository = "ananthb/mandapam-theme"
  [params.homepage_meta_tags]
    meta_description = "Lorem ipsum dolor sit amet consectetur adipiscing elit"
    meta_og_title = "Lorem Mandapam"
    meta_og_type = "website"
    meta_og_url = "https://example.com"
    meta_og_image = "https://example.com/images/venue.jpg"
    meta_og_description = "Lorem ipsum dolor sit amet consectetur adipiscing elit"
    meta_twitter_card = "summary_large_image"
    meta_twitter_site = "@lorem"
    meta_twitter_creator = "@lorem"

[menus]
  [[menus.main]]
    name = "Domus"
    url = "/"
    weight = 10
  [[menus.main]]
    name = "Locus"
    url = "/venue/"
    weight = 20
  [[menus.main]]
    name = "Facilitates"
    url = "/facilities/"
    weight = 30
  [[menus.main]]
    name = "Imago"
    url = "/gallery/"
    weight = 40
  [[menus.main]]
    name = "Contactus"
    url = "/contact/"
    weight = 50

[module]
  [[module.imports]]
    path = "github.com/ananthb/mandapam-theme"
